---
name: Flag outdated files

on:
  pull_request: # temporary, just to test the workflow
  # later add schedule and manual triggers

permissions:
  contents: read
  issues: write

jobs:
  some_name:
    runs-on: ubuntu-24.04

    steps:
      # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v7

      # 2. Setup Python 3.13
      - name: Setup Python 3.13
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      # 3. Install python-frontmatter
      - name: Install python-frontmatter
        run: pip install python-frontmatter

      # 3. Run Python script
      # use excluded paths file as input variable
      # let python handle repo contents and find the correct files to check
      - name: Run python script
        run: python .config/flag-outdated/check_for_last_reviewed.py .config/flag-outdated/excluded-paths.txt

      - name: Check if there's an existing issue
        id: last-issue
        uses: micalevisk/last-issue-action@v2
        with:
          state: open
          labels: flag-outdated

      - name: Create issue from file
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Outdated files
          content-filepath: ./outdated-results.md
          issue-number: ${{ steps.last-issue.outputs.issue-number }}
          labels: flag-outdated
