# 1. scanna repot -- yml
# 2. bestämma vilka filer som ska ha en last_review date -- yml
# 3. kolla igenom alla de filerna och se om dom har det -- python
# 4. om dom inte har det, lägg i en lista som ska visas i en issue -- python
# 5. om dom har det, kolla om det är i rätt format, och om inte lägg i en lista som ska visas i en issue -- python
# 6. om formatet är rätt, jämför med dagens datum -- python
# 7. om det är äldre än 12 månader, lägg i en lista som ska visas i en issue -- python
---
name: Flag outdated files

on:
  pull_request: # temporary, just to test the workflow
  # later add schedule and manual triggers

permissions:
  contents: read

jobs:
  some_name:
    runs-on: ubuntu-24.04

    steps: 
      # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v7            

      # 2. Setup Python 3.13
      - name: Setup Python 3.13
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      
      # 3. Run Python script
      # use excluded paths file as input variable
      # let python handle repo contents and find the correct files to check
      - name: Run python script
        run: python .config/flag-outdated/check_for_last_reviewed.py .config/flag-outdated/excluded-paths.txt
      
      # 4. Print output or let python do it? 
